### Functions ###

function killapp() {
	kill -9 $(ps aux | grep $1 | grep -v grep | awk '{print $2}')
}

function isrunning() {
	ps aux | grep $1 | grep -v grep | awk '{print $2}'
}

function password() {
    count=${1:-20}
    echo "$(LC_ALL=C tr -dc "[:graph:]" < /dev/urandom | head -c ${count})"
}

function whoknocks() {
    customPort=$1

    if [ "$customPort" = "" ]; then
        echo "✊🏻 Knocking at default port: 8080"
        lsof -n -i4TCP:8080
    else
        echo "✊🏻 Knocking at port: $customPort"
        lsof -n -i4TCP:$customPort
    fi
}

function git-parent-branch() {
	current_branch=`git rev-parse --abbrev-ref HEAD`
	git show-branch -a | awk -F'[]^~[]' '/\*/ && !/'"$current_branch"'/ {print $2;exit}'
}

function git-untrack-file() {
	git update-index --assume-unchanged $1
}

function git-trackfile() {
	git update-index --no-assume-unchanged $1
}

# Docker functions
function cleardocker() {
    echo "🧹 Clearing docker stuff"
    killcontainers | deletedockerimages
    echo "🐳 We\'re ready to rock"
}

function deletedockerimages() {
    echo "🗑 Deleting all docker images ... "
    docker images -q | xargs docker rmi
}

function stopcontainers() {
    docker stop $(docker ps -a -q)
}

function killcontainers() {
    echo "⏹ Stoping containers ..."
    docker stop $(docker ps -a -q)

    echo "🚮 Removing containers ..."
    docker rm $(docker ps -a -q)

    echo "✅ Containers Stoped!"
}

### End Functions ###

### Env Vars ###

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

### End Env Vars ###

### Aliases ###

alias la="ls -laish"
alias datenow=echo $(date '+%y.%m.%d-%H%M')
alias ip="ifconfig | grep \"inet \" | grep -v 127.0.0.1 | cut -d\  -f2"
alias reload="source ~/.zshrc"

### End Aliases ###
